### ISSUE TITLE
New: OREL events calendar | spreadsheet

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Admin#11]
Semi-automated gsheet to keep track of upcoming events & deadlines

https://docs.google.com/spreadsheets/d/1U0cm3qOnvgxpqOpmH0fsDKGP9j86KN3OFU9mdW8lyr4/edit?usp=sharing

- [x] demo

- [ ] add - slack thread link options / other github orgs?

**Comment by jesparent** [comment]
Make a link to specific slack threads?

**Comment by jesparent** [comment]
Also - What about doing this for resources in general / papers/ links etc? For weekly meetings? how would this mesh with zotero / citation management?" 


@Orthogonal-Research-Lab  thoughts?

**Comment by Orthogonal-Research-Lab** [comment]
Can we make the events calendar interface with Slack/Website? Not sure about how this will mesh with Zotero. We should definitely put the automation processes on the lab meeting agenda.

**Comment by jesparent** [comment]
@Orthogonal-Research-Lab  I'm essentially using Zapier right now, and there may be some ways to mesh with Slack. Would you want slack to be an Input or an Output? I'll mention more details within our channel

**Comment by jesparent** [comment]
@Orthogonal-Research-Lab do you think this is basically obsolete now with the newer version that you've made? Also any chance you could move that which you made into the OREL Admin google folder and/or give others write access to it?

**Comment by Orthogonal-Research-Lab** [comment]
Well, we have a deadlines calendar, but not for educational and other
external events. We might do this with another Google Sheet, but I am still
not satisfied with the implementation.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
