### ISSUE TITLE
OREL Planning for 2020

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Admin#13]
@channel team OREL, some thoughts about what is ahead:
There are so many different potential projects we could be developing into 2021. I'd like to suggest we take some time in the next few weeks to hash some of them out and maybe vet them with the lab. Actual projects that would test some ideas and research them ; some of the cataloguing things that I'm doing in #cognition-futures currently ; Anson's allostasis work (unifying some things in the AI-Neuro space ala Main2020) ; past ties to #virtual-reality; Bradly being hype about the Continuous Learning tutorial also at MAIN ; A throwback to Sam F's older work came up recently ; and no less the actual Developmental AI  / #meta-brain-models flagship project that we've had going on.
This is part lab manager and part... developing researcher learning about project management and directing actual academic activity. But I think some of these things can be distilled into micro-proposals or visions, and frankly some of these things I know I have friends who are interested in and could lead to a call for involvement with them. So let's think about this some, mm.

**Comment by balicea** [comment]
Great! Let's talk about this at tomorrow's meeting.
