### ISSUE TITLE
SIGCHI: Revisions

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Admin#18]

**Comment by Athene-ai** [comment]
Let me know  :)

**Comment by jesparent** [comment]
The Event
The workshop will run on the 15th May
15 May JST 1300-1700 / 15 May EDT 0000-0400 / 15 May CEST 0600-1000

This year, to respond to the need to run things virtually we'll be running some aspects asynchronously. In part this is because a full day of workshop in person works well, while a full day of video-conferencing is exhausting. More details of all this will be sent out in the next few weeks but roughly:

1) We plan to move presentations of papers online, and ahead of the workshop.  Rather than presenting on the day, participants will upload short video presentations (< c5 mins). We will make these available to all participants for viewing in the weeks before the conference. Provisional deadline for presentation videos - 18th April

2) At about the same time, we will open a slack channel to begin discussion. This will allow participants to ask questions about each others' work, and define discussion points for the day.

3) On the day we will focus on structured discussion, and a final panel discussion with Q&A.

4) An aim of the workshop is to create publications outlining the issues discussed and the routes forward proposed. As such we will be organising a follow up meeting for in the months after the conference. We will have more flexibility around time and place when organising this.

"Camera Ready" Papers
If you will make any changes to your paper, please submit the final version by 11th April

Registration
Registration for CHI workshops is $30/workshop and attendees must also register for at least one day of the conference. Registration is cheaper this year than usual.


[...........]
