### ISSUE TITLE
Embryo Networks as Generative Divergent Integration 

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Admin#30]
https://docs.google.com/presentation/d/18iUCqFh-fXevOIG5YIKq6OoEHJFy0FGg6TaxG2nz7vY/edit#slide=id.gd6949316a0_0_360

**Comment by jesparent** [comment]
It looks like this is all set - but @balicea  let me know if there were any other updates.

**Comment by Orthogonal-Research-Lab** [comment]
All set for this issue.
