### ISSUE TITLE
GECCO 2022 : Switching paper

### ISSUE THREAD

**Issue by jesparent** [OREL-group/Admin#56]
Link:
Website:
Google Doc sharable link to paper / draft:

**Comment by jesparent** [comment]
@Agrover112  could you edit the description field above here in this issue with information about the conference or the paper? I think I missed wherever this was originally mentioned.

**Comment by Agrover112** [comment]
> @Agrover112  could you edit the description field above here in this issue with information about the conference or the paper? I think I missed wherever this was originally mentioned. 

I don't have edit acess

**Comment by jesparent** [comment]
closing this out but @Agrover112 feel free to add more
