### ISSUE TITLE
Create Repo for Synthetic Daisies

### ISSUE THREAD

**Issue by Orthogonal-Research-Lab** [OREL-group/Admin#7]

**Comment by jesparent** [comment]
@Orthogonal-Research-Lab  - I was considering making a "SciComm" repo for dsicussion of writings taht are not "papers" or events abstract -but things like blogs (which SD is), or other things, like Gradient, Medium, and other outlets that are more public and less Academic journals. Any thoughts of this?

**Comment by Orthogonal-Research-Lab** [comment]
You could call it SciComm, but "blogging" might be better, since we might blog about things that are not yet papers, but are quite dense (Synthetic Daisies has a long tradition of this). By the way, Synthetic Daisies has its own Github repo: https://github.com/synthetic-daisies

**Comment by jesparent** [comment]
Ohhhh - nice! You made an ORG account for it?: I think that's a good idea. Ok. I might Update based on that input.

**Comment by jesparent** [comment]
> 
> 
> You could call it SciComm, but "blogging" might be better, since we might blog about things that are not yet papers, but are quite dense (Synthetic Daisies has a long tradition of this). By the way, Synthetic Daisies has its own Github repo: https://github.com/synthetic-daisies

I've made a "writings" repo that I think will be  more in line witht he blog and general non-journal writings. Let me know if that works.
